"""Render manuscript/results prose from recorded v0.2 experiment data."""
import json,re,subprocess,shutil,os,sys,tomllib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'results/revision';PAPER=ROOT/'paper';C=tomllib.loads((ROOT/'config.toml').read_text());E=C['revision'];S=json.loads((OUT/'summary.json').read_text());X=json.loads((OUT/'external/summary.json').read_text());ENV=json.loads((OUT/'environment.json').read_text());F=PAPER/'figures'
f=lambda x:format(x,'.3g')
def table(headers,rows):return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(map(str,row))+' |' for row in rows])
R=S['reconstruction'];P=S['performance'];T=S['tints_common'];SS=S['random_smoothness'];V={}
V.update(N=E['random_colors'],NP=E['random_pairs'],SEED=E['seed'],STEPS=E['trajectory_steps'],TRAJ=E['random_trajectories'],BN=E['benchmark_iterations'],REPEATS=E['benchmark_repeats'],TINT_COUNT=T['eligible'],CPU=ENV['cpu_model'],RUST=ENV['rustc'])
V.update(OLD_RAW=f(R['v0.1 raw']['deltaE00']['mean']),NEW_RAW=f(R['v0.2 raw']['deltaE00']['mean']),RAW_MAX=f(R['v0.2 raw']['deltaE00']['max']),CORRECT_MEAN=f(R['v0.2 corrected']['deltaE00']['mean']),CORRECT_MAX=f(R['v0.2 corrected']['deltaE00']['max']),OLD_GREEN=f(100*S['holdout_green_fraction']['v0.1']),NEW_GREEN=f(100*S['holdout_green_fraction']['v0.2']),REF_MEAN=f(S['fast_vs_reference']['mean']),REF_P95=f(S['fast_vs_reference']['p95']),REF_MAX=f(S['fast_vs_reference']['max']),FULL_MPS=f(P['v0.2 RGB']['million_per_second']),CACHE_MPS=f(P['v0.2 cached']['million_per_second']))
V.update(NEW_BYTES=340,OLD_BYTES=44,FAST_COEFF_BYTES=(8+3+1)*41*4,LUT_BYTES=(ROOT/'data/default.lut').stat().st_size,PY_REF=f(S['rust_python_ref_max_linear']),F32_MEAN=f(S['fast_vs_python_same_step']['mean']),DEC_PRECISION=f(S['decoder_precision_max']),ONE_MEAN=f(S['resolution'][0]['mean']),ONE_MAX=f(S['resolution'][0]['max']),GAMUT_PERCENT=f(100*S['gamut_fraction']),RAW_RANGE=str([round(x,5) for x in S['raw_range']]))
for model,prefix in [('v0.1','OLD'),('v0.2','NEW')]:
 V[prefix+'_TINT_MED']=f(T[model]['median']);V[prefix+'_TINT_P95']=f(T[model]['p95']);V[prefix+'_STEP']=f(SS[model]['max']);V[prefix+'_STEP_P99']=f(SS[model]['p99']);V[prefix+'_PERT']=f(S['input_perturbations'][model]['max'])
V['BLACK_STEP']=f(S['tints']['black_endpoint_max_step']);V['LINEAR_BLACK_STEP']=f(next(x['max_step'] for x in S['canonical_smoothness'] if x['pair']=='black_white' and x['method']=='linear'))
for token,k,stat in [('OLD_MB','old_vs_mixbox','mean'),('NEW_MB','new_vs_mixbox','mean'),('MAX_MB','new_vs_mixbox','max'),('SPEC_MB','spectral_vs_mixbox','mean'),('OLD_SPEC','old_vs_spectral_all','mean'),('NEW_SPEC','new_vs_spectral_all','mean')]:V[token]=f(X[k][stat])
V['GRID_MAX']=f(S['grid_reconstruction']['max_srgb_channel_error']);V['GRID_DE']=f(S['grid_reconstruction']['deltaE00']['max'])
keys=['mean','median','p95','p99','max']
V['RECON_TABLE']=table(['Reconstruction','Mean','Median','P95','P99','Max'],[[k]+[f(v['deltaE00'][s]) for s in keys] for k,v in R.items()])
V['RESOLUTION_TABLE']=table(['Spacing (nm)','Mean','P95','Max'],[[r['step_nm']]+[f(r[k]) for k in ['mean','p95','max']] for r in S['resolution']])
V['MIDPOINT_TABLE']=table(['Pair','v0.1 sRGB8','v0.2 sRGB8'],[[r['pair'].replace('_',' + '),str(tuple(r['v0.1'])),str(tuple(r['v0.2']))] for r in S['midpoints']])
V['PERF_TABLE']=table(['Operation','Median ns','Million/s'],[[k,f(v['median']),f(v['million_per_second'])] for k,v in P.items()])
text=(ROOT/'tools/revision/paper.template.md').read_text()
for k,v in V.items():text=text.replace('@'+k+'@',str(v))
assert not re.search(r'@[A-Z_]+@',text),'Unsubstituted paper token'
(PAPER/'paper.md').write_text(text);(PAPER/'tables/revision-values.json').write_text(json.dumps(V,indent=2)+'\n');(PAPER/'tables/revision-summary.json').write_text(json.dumps(S,indent=2)+'\n')
bench='# Benchmarks and numerical results, v0.2\n\nGenerated from `results/revision/`. Both versions use the same current-run samples and machine; historical v0.1 timings remain in `paper/legacy`. No results are real-paint accuracy measurements.\n\n'+V['PERF_TABLE']+'\n\n'+ENV['cpu_model']+'; '+ENV['rustc']+'; release, single thread, LTO off, codegen-units=1. Seven repetitions of 100,000 operations. Complete RGB timings include two encodes and one display decode; cached timings omit encodes. Full new RGB mixing is slower than the old LUT model, while the new reference avoids nonlinear inversion.\n\n## Reconstruction (CIEDE2000)\n\n'+V['RECON_TABLE']+'\n\nCorrected accuracy follows from the residual identity and does not validate inferred material. Raw error is substantially smaller, but the spectral floor still limits dark colors.\n\n## Fast/reference approximation\n\n'+V['RESOLUTION_TABLE']+'\n\nThis table changes wavelength sampling in f64 while holding the fitted spectra fixed. The 1 nm row interpolates the 5 nm spectra. Actual f32 fast/reference mean, P95 and max: '+V['REF_MEAN']+', '+V['REF_P95']+', '+V['REF_MAX']+' ΔE2000. Same-grid float32/Python mean: '+V['F32_MEAN']+'. Promoted decoder max channel error: '+V['DEC_PRECISION']+'.\n\n## Quality diagnostics\n\nHeld-out green-dominant fraction: '+V['OLD_GREEN']+'% → '+V['NEW_GREEN']+'%. Common-set tint hue P95: '+V['OLD_TINT_P95']+'° → '+V['NEW_TINT_P95']+'°. Random max adjacent ΔEOK100: '+V['OLD_STEP']+' → '+V['NEW_STEP']+'; P99 did not uniformly improve. Pure-black first tint step remains '+V['BLACK_STEP']+' at Δt=.001, comparable to linear RGB '+V['LINEAR_BLACK_STEP']+'.\n\n## External comparisons\n\nMean difference from 39 Mixbox JPEG observations: '+V['OLD_MB']+' → '+V['NEW_MB']+' ΔE2000. Mean difference from 5,213 Spectral.js 3.0 API samples: '+V['OLD_SPEC']+' → '+V['NEW_SPEC']+'. These are similarity measures only. No external outputs were fitting targets.\n\n## Reproduce\n\n`python3 tools/reproduce.py`. Raw repetitions, exact seeds, configurations, inputs, outcomes and environment are bundled. The new default has no runtime LUT parse; construction is a zero-sized value. Its 340-byte latent is larger than the 44-byte legacy latent.\n'
(ROOT/'docs/benchmarks.md').write_text(bench)
report='# Mathematical revision: what changed and what it achieved\n\nVersion 0.2 replaces the ambiguous finite-palette inverse with smooth spectral reconstruction and an explicit absorption/scattering strength prior. It uses no new paint measurements and no coefficients or fitting targets from another engine.\n\n'+V['MIDPOINT_TABLE']+'\n\n![Comparisons](../paper/figures/comparisons.png)\n\n## Measured changes\n\n'+V['RECON_TABLE']+'\n\nRaw mean error falls from '+V['OLD_RAW']+' to '+V['NEW_RAW']+' ΔE2000. Held-out green-dominant frequency rises from '+V['OLD_GREEN']+'% to '+V['NEW_GREEN']+'%. Tint hue P95 falls from '+V['OLD_TINT_P95']+'° to '+V['NEW_TINT_P95']+'° on '+str(V['TINT_COUNT'])+' common eligible colors. These are model diagnostics, not physical paint measurements.\n\n'+V['PERF_TABLE']+'\n\n## Tradeoffs and remaining failures\n\nThe full RGB and cached operations are slower than v0.1, and cached state grows from 44 to 340 bytes. Some saturated red/blue mixtures are more muted. Not every blue/yellow color family result is green. The P99 random-trajectory statistic does not uniformly improve. Near black, the finite-step OKLab distance remains large, though endpoint refinement confirms continuity. White strength is a chosen prior, not calibrated titanium white.\n\n## Mixbox and Spectral.js\n\n![External comparison](../paper/figures/external_comparison.png)\n\nMixbox sample mean distance falls from '+V['OLD_MB']+' to '+V['NEW_MB']+' ΔE2000; all-curve Spectral.js distance falls from '+V['OLD_SPEC']+' to '+V['NEW_SPEC']+'. We selected our model before inspecting these comparisons. Mixbox values are JPEG samples at three t values; the screenshot control has roughly 0.29 mean ΔE uncertainty. Similarity does not establish which engine is closest to real paint.\n\nSee the main paper, `docs/math.md`, `docs/coefficients.md`, `docs/revision-decisions.md` and raw `results/revision` data. Run `python3 tools/reproduce.py` to regenerate. The old implementation is available as `ochrell::legacy`.\n'
(ROOT/'docs/revision-report.md').write_text(report)
if not shutil.which('pandoc'):print('Markdown generated; Pandoc unavailable.');sys.exit(0)
os.chdir(PAPER)
subprocess.run(['pandoc','paper.md','--standalone','--citeproc','--resource-path=.', '-V','documentclass=article','-V','classoption=twocolumn','-V','fontsize=10pt','-V','geometry:margin=0.7in','-V','colorlinks=true','--bibliography=references.bib','-o','paper.tex'],check=True)
tex=Path('paper.tex').read_text();titles=iter(['Source reconstruction (CIEDE2000), identical sample set.','Sampling discrepancy from the 5 nm computational reference.','Canonical half-mixture colors.','Single-thread runtime; cached states omit input encoding.'])
def convert(m):
 block=re.sub(r'\\endfirsthead.*?\\endhead','',m.group(1),flags=re.S)
 block=block.replace('\\columnwidth','\\textwidth')
 for x in ['\\endhead','\\endlastfoot','\\endfoot']:block=block.replace(x,'')
 return '\\begin{table*}[t]\n\\caption{'+next(titles)+'}\n\\centering\\small\n\\begin{tabular}'+block+'\\end{tabular}\n\\end{table*}'
tex=re.sub(r'\\begin\{longtable\}\[\](.*?)\\end\{longtable\}',convert,tex,flags=re.S)
tex=tex.replace('\\begin{figure}','\\begin{figure*}[t]').replace('\\end{figure}','\\end{figure*}')
tex=re.sub(r'\\includegraphics(?:\[[^\]]*\])?\{(figures/[^}]+)\}',r'\\includegraphics[width=0.94\\textwidth,height=0.72\\textheight,keepaspectratio]{\1}',tex)
tex=tex.replace('Δ',r'\ensuremath{\Delta}').replace('β',r'\ensuremath{\beta}').replace('¼',r'\ensuremath{1/4}').replace('½',r'\ensuremath{1/2}').replace('¾',r'\ensuremath{3/4}')
tex=tex.replace('\\begin{document}','\\setlength{\\emergencystretch}{2em}\n\\sloppy\n\\begin{document}')
Path('paper.tex').write_text(tex)
if shutil.which('pdflatex'):
 for _ in range(2):
  p=subprocess.run(['pdflatex','-interaction=nonstopmode','-halt-on-error','paper.tex'],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
  if p.returncode:Path('build-error.txt').write_text(p.stdout);raise RuntimeError(p.stdout[-3000:])
 print('Generated revised paper Markdown, TeX, PDF and results documents.')
