"""Generate only the opt-in Synthetic Four reference. Python standard library only.

Inputs are original analytic paint definitions and the existing attributed CIE
subset. No measured paint, comparator data, legacy palette or RGB fit is used.
Run with --check to verify tracked assets without writing files.
"""
import argparse
import csv
import hashlib
import json
import math
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
DEFINITION = ROOT / "data/palettes/synthetic-four-v1.json"
CIE = ROOT / "data/cie_380_780_1nm.csv"
MATRIX = (
    (3.2409699419045226, -1.537383177570094, -0.4986107602930034),
    (-0.9692436362808796, 1.8759675015077202, 0.04155505740717559),
    (0.05563007969699366, -0.20397695888897652, 1.0569715142428786),
)


def smoothstep(nm, start, end):
    if end <= start:
        raise ValueError("A spectral transition must have positive width")
    t = min(1.0, max(0.0, (nm - start) / (end - start)))
    return t * t * (3.0 - 2.0 * t)


def generate():
    definition = json.loads(DEFINITION.read_text(encoding="utf-8"))
    if definition["optical_prior"] != "s = strength / sqrt(1 + q), k = q * s, q = (1-r)^2 / (2*r)":
        raise ValueError("Unsupported optical prior; update the generator explicitly")
    if definition["amount_basis"] != "relative synthetic material amounts":
        raise ValueError("This generator does not calibrate physical amount units")
    if definition["grid"] != {"start_nm": 380, "end_nm": 780, "step_nm": 5}:
        raise ValueError("This reference format requires the 81-band 380-780 nm grid")
    paints = definition["paints"]
    if [p["name"] for p in paints] != ["yellow", "red", "blue", "white"]:
        raise ValueError("This built-in reference requires yellow, red, blue, white in that order")
    with CIE.open(encoding="utf-8", newline="") as stream:
        cie = {int(row["nm"]): row for row in csv.DictReader(stream)}
    k, s, xyz = [], [], []
    for nm in range(380, 781, 5):
        kr, sr = [], []
        for paint in paints:
            r = paint["floor"]
            for start, end, gain in paint["rising"]:
                r += gain * smoothstep(nm, start, end)
            for start, end, gain in paint["falling"]:
                r += gain * (1.0 - smoothstep(nm, start, end))
            if not 0.0 < r <= 1.0 or not math.isfinite(paint["strength"]) or paint["strength"] <= 0:
                raise ValueError("Invalid reflectance or optical strength")
            q = (1.0 - r) ** 2 / (2.0 * r)
            scattering = paint["strength"] / math.sqrt(1.0 + q)
            kr.append(q * scattering)
            sr.append(scattering)
        k.append(kr)
        s.append(sr)
        row = cie[nm]
        weight = 0.5 if nm in (380, 780) else 1.0
        xyz.append([weight * float(row["D65"]) * float(row[ch]) for ch in ("xbar", "ybar", "zbar")])
    # Trapezoidal integration; the uniform 5 nm factor cancels in normalization.
    normalizer = sum(row[1] for row in xyz)
    xyz = [[v / normalizer for v in row] for row in xyz]
    rgb = [[sum(a * b for a, b in zip(row, channel)) for channel in MATRIX] for row in xyz]
    white = [sum(row[ch] for row in rgb) for ch in range(3)]
    rgb = [[row[ch] / white[ch] for ch in range(3)] for row in rgb]

    # Identity includes the exact generated optical and projection values, paint
    # order, conventions and generator source. It is embedded in saved recipes.
    source_hash = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    cie_hash = hashlib.sha256(CIE.read_bytes()).hexdigest()
    identity = hashlib.sha256(b"ochrell-palette-reference-v1\0")
    identity.update(json.dumps(definition, sort_keys=True, separators=(",", ":")).encode("utf-8"))
    identity.update(bytes.fromhex(cie_hash))
    identity.update(bytes.fromhex(source_hash))
    for table in (k, s, rgb):
        for row in table:
            for value in row:
                identity.update(struct.pack("<d", value))
    digest = identity.digest()

    def table(name, values, columns):
        rows = ["    [" + ", ".join(format(x, ".17e") for x in row) + "]," for row in values]
        return f"#[rustfmt::skip]\npub const {name}: [[f64; {columns}]; 81] = [\n" + "\n".join(rows) + "\n];"

    rust = "\n".join([
        "// Generated by tools/generate_palette.py. Do not edit by hand.",
        "// CIE-derived quadrature: CC BY-SA 4.0; original synthetic definitions: MIT OR Apache-2.0.",
        "// See data/README.md and docs/palette-reference.md for provenance and conventions.",
        f"pub const ID: &str = {json.dumps(definition['id'])};",
        "pub const NAMES: [&str; 4] = " + json.dumps([p["name"] for p in paints]) + ";",
        "#[rustfmt::skip]\npub const FINGERPRINT: [u8; 32] = [" + ", ".join(str(x) for x in digest) + "];",
        table("K", k, 4), table("S", s, 4), table("RGB", rgb, 3), "",
    ])
    manifest = {
        "palette_id": definition["id"],
        "palette_sha256": digest.hex(),
        "definition_sha256": hashlib.sha256(DEFINITION.read_bytes()).hexdigest(),
        "generator_sha256": source_hash,
        "cie_subset_sha256": cie_hash,
        "generated_rust_sha256": hashlib.sha256(rust.encode("utf-8")).hexdigest(),
        "provenance": "Original synthetic smoothstep spectra; no measured paint or comparator fitting",
        "projection": "CIE 1931 2 degree / D65, 380-780 nm / 5 nm trapezoid, neutral normalized linear sRGB",
        "data_license": "CIE-derived quadrature and combined generated asset: CC BY-SA 4.0; retain data/README.md notices",
    }
    return {
        ROOT / "src/palette_generated.rs": rust,
        ROOT / "data/palettes/synthetic-four-v1-manifest.json": json.dumps(manifest, indent=2) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_bytes() != content.encode("utf-8"):
                raise SystemExit(f"Generated asset differs: {path.relative_to(ROOT)}")
        else:
            path.write_bytes(content.encode("utf-8"))
        print(f"{'Verified' if args.check else 'Wrote'} {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
