from model import *
import hashlib,json
out=['// @generated by tools/generate_model.py; CIE-derived weights: see data/README.md.']
def arr(name,a,ty='f64'):
 a=np.asarray(a);shape=''.join('[' for _ in a.shape)+ty+''.join('; '+str(n)+']' for n in a.shape[::-1])
 def fmt(x):
  if np.ndim(x):return '['+','.join(fmt(y) for y in x)+']'
  return format(float(x),'.17e')
 out.append(f'pub const {name}: {shape} = {fmt(a)};')
for step,suffix,ty in [(5,'REF','f64'),(20,'FAST','f32')]:
 m=Model(step)
 arr('K_'+suffix,m.k.T,ty);arr('RGB_'+suffix,m.rgb,ty);arr('S_'+suffix,m.s,ty)
arr('REG',[CFG['model']['regularization']])
out.append('pub const SOLVER_ITERATIONS: usize = '+str(CFG['model']['solver_iterations'])+';')
(ROOT/'src/generated.rs').write_text('\n'.join(out)+'\n')
# Temporary zero table only bootstraps the generator; never a delivered model.
f=ROOT/'data/default.lut'
if not f.exists():f.write_bytes(b'PMX1'+(2).to_bytes(4,'little')+np.zeros((8,8),dtype='<f4').tobytes())
(ROOT/'data/model_manifest.json').write_text(json.dumps({'config_sha256':hashlib.sha256((ROOT/'config.toml').read_bytes()).hexdigest(),'cie_subset_sha256':hashlib.sha256((ROOT/'data/cie_380_780_1nm.csv').read_bytes()).hexdigest(),'generator':'tools/generate_model.py','colour_version':'0.4.6'},indent=2)+'\n')
