"""Generate only the CIE/D65 400-700 nm preview quadrature, without paint data."""
import argparse
import csv
import hashlib
from pathlib import Path
from generate_palette import MATRIX

ROOT=Path(__file__).resolve().parents[1]


def projection():
    with (ROOT/'data/cie_380_780_1nm.csv').open(encoding='utf-8',newline='') as f:
        cie={int(r['nm']):r for r in csv.DictReader(f)}
    xyz=[]
    for nm in range(400,701,10):
        row=cie[nm]; weight=.5 if nm in (400,700) else 1.
        xyz.append([weight*float(row['D65'])*float(row[ch]) for ch in ('xbar','ybar','zbar')])
    normalizer=sum(row[1] for row in xyz)
    xyz=[[v/normalizer for v in row] for row in xyz]
    rgb=[[sum(a*b for a,b in zip(row,channel)) for channel in MATRIX] for row in xyz]
    white=[sum(row[ch] for row in rgb) for ch in range(3)]
    return [[row[ch]/white[ch] for ch in range(3)] for row in rgb]


def generate():
    cie_hash=hashlib.sha256((ROOT/'data/cie_380_780_1nm.csv').read_bytes()).hexdigest()
    rows=['    ['+', '.join(format(v,'.17e') for v in row)+'],' for row in projection()]
    return ('// Generated by tools/generate_window_projection.py; no paint measurements.\n'
        '// CIE-derived data: CC BY-SA 4.0; see data/README.md.\n'
        '// Windowed D65 preview only, 400-700 nm / 10 nm; neutral-normalized sRGB.\n'
        f'// CIE input SHA256: {cie_hash}\n'
        '#[rustfmt::skip]\npub const RGB: [[f64; 3]; 31] = [\n'+'\n'.join(rows)+'\n];\n').encode()


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    p=ROOT/'src/palette_window.rs'; data=generate()
    if args.check: assert p.read_bytes()==data
    else: p.write_bytes(data)
