"""Build the integration report from retained observations, not hand-entered tables."""
import csv
import json
from pathlib import Path
import statistics

ROOT=Path(__file__).resolve().parents[1]
R=ROOT/"results/integration"
s=json.loads((R/"integration-summary.json").read_text())
m=json.loads((R/"mixbox/summary.json").read_text())

def rows(name):
    return list(csv.DictReader((R/name).open(encoding="utf-8-sig")))

def median(data,key,value,field):
    return statistics.median(float(r[field]) for r in data if r[key]==value)

native=rows("mixbox/native-mixing.csv")
kernel=rows("kernel-benchmark.csv")
adapter=rows("mixbox/python-adapter.csv")
out=["# Oil-paint integration: measured results", "",
"Generated by `python tools/integration_report.py` from `results/integration/`.",
"These are synthetic-model and implementation measurements, not real-paint accuracy.", "",
"## Conditions", "",
"Windows x64, Intel Core Ultra 7 258V, 8 cores, rustc 1.91.1 MSVC, Python 3.12.11.",
"Native mixing is one thread, release, codegen-units=1, LTO off. Both cached", 
"mixer kernels are compiled in the same comparison executable. Fixed seed", 
"20260930; seven native repetitions after warmup, 500,000 operations each;",
"4,096 source colors. OpenCV lighting uses one thread in brush benchmarks.",
"Python package versions, source hashes, inputs and raw repetitions are retained.",
"Shared-host scheduling and CPU frequency cause timing variation; these are not", 
"cross-platform guarantees. No explicit SIMD, GPU or browser work was added.", "",
"## Native mixing", "", "| Operation | Mixbox ns | Ochrell ns | Ochrell / Mixbox |", "|---|---:|---:|---:|"]
for title,a,b in [("Preserved state interpolation","mixbox_state_mix","ochrell_state_mix"),
                  ("Decode to sRGB","mixbox_decode","ochrell_decode"),
                  ("Cached mix + decode","mixbox_cached_mix_decode","ochrell_cached_mix_decode")]:
    ma=median(native,"method",a,"ns_per_operation");mb=median(native,"method",b,"ns_per_operation")
    out.append(f"| {title} | {ma:.2f} | {mb:.2f} | {mb/ma:.2f}x |")
out += ["",f"Ochrell encode: {median(native,'method','ochrell_encode','ns_per_operation'):.2f} ns. "
        f"Full RGB-in pair mixing: {median(native,'method','ochrell_full_rgb','ns_per_operation'):.2f} ns.",
"The renderer has no native Mixbox encoder, so there is no claimed native full-RGB", 
"comparison. Mixbox states are prepared through its existing NumPy encoder in a", 
"temporary file. No LUT, source or coefficients are exported into Ochrell.", "",
"## Actual Python adapters", "",
"Median microseconds per color, including validation, allocations, NumPy or ctypes.",
"Full mixing includes two encodes and one decode. This measures the available", 
"integration paths, not just algorithm cost; small batches mainly measure Python.", "",
"| Batch | Operation | Mixbox us/color | Ochrell us/color |", "|---:|---|---:|---:|"]
for batch in (1,64,1024,4096):
    for op in ("encode","decode","full_rgb_mix"):
        values=[]
        for backend in ("mixbox","ochrell"):
            values.append(statistics.median(float(r["ns_per_color"])/1000 for r in adapter if int(r["batch"])==batch and r["operation"]==op and r["backend"]==backend))
        out.append(f"| {batch} | {op} | {values[0]:.3f} | {values[1]:.3f} |")
out += ["", "## Brush replay and surface rendering", "",
"Identical authored RGB inputs, paths, brush parameters and seeds exercise", 
"yellow/blue, white, black, 12-pass four-color buildup, pickup, smudge, scumble,", 
"marbling, dry tails, dry underpaint and the RGB glaze approximation.",
"The original Mixbox renderer uses alpha as mixture weight and a seven-float", 
"state. The matched Mixbox control pads that state to 85 floats and uses the", 
"same paint-amount transport and coverage compositing as Ochrell. Thus the", 
"matched control isolates mixer behavior/cost within this integration, while", 
"the original shows the existing renderer's actual lighter memory/workload.", "",
"| Width | Method | Paint ms | Lighting ms | Canvas MB |", "|---:|---|---:|---:|---:|"]
for width,methods in m["brush"].items():
    for method,v in methods.items():
        out.append(f"| {width} | {method} | {1000*v['paint_seconds_median']:.1f} | {1000*v['lighting_seconds_median']:.1f} | {v['canvas_bytes']/1e6:.2f} |")
out += ["", "Painting includes Python stroke validation/dispatch and native rasterization;", 
"it excludes stroke encoding, allocation, layer blur/drying, lighting and file IO.", 
"Those phases have separate raw timing fields. These are offline brush workloads,", 
"not evidence of a 60 Hz interactive application. Native timing is measured below", 
"the FFI boundary in the separate mixing table.", "",
"![Mixbox and Ochrell with original and matched transport](../results/integration/mixbox/mixbox-comparison-lit.png)", "",
"The unlit comparison is `results/integration/mixbox/mixbox-comparison-unlit.png`.",
"Height, amount, coverage and wetness agree in matched-control tests. All repeated", 
"brush images are deterministic on this host. Differences between mixer images", 
"are similarity observations, not accuracy rankings.", "",
"## Keeping material history", "",
"| Width | Persistent paint ms | RGB-roundtrip paint ms | Mean / P95 / max display difference (DE2000) |",
"|---:|---:|---:|---|"]
for width,methods in s["brush"].items():
    p=methods["ochrell"];r=methods["ochrell-roundtrip"];d=r["vs_persistent_deltaE2000"]
    out.append(f"| {width} | {1000*p['paint_seconds_median']:.1f} | {1000*r['paint_seconds_median']:.1f} | {d['mean']:.3f} / {d['p95']:.3f} / {d['max']:.3f} |")
out += ["", "![Persistent states, RGB round trips and sRGB](../results/integration/brush-comparison-unlit.png)", "",
"The roundtrip control reconstructs material at canvas updates and brush", 
"pickup/replenishment. It can preserve a displayed color immediately yet change", 
"its future tint or pickup behavior. Errors need not grow monotonically: the", 
"256-step color error can be lower than 64 steps, yet a subsequent white addition", 
"again reveals the lost material. Persistent state preserves weighted grouping.", "",
"## Reference and candidate storage errors", "",
"2,048 deterministic samples per main case; 128 samples for the 4,096-step tiny", 
"pickup test. Reference is the existing 81-band f64 synthetic model. Table cells", 
"are mean / maximum DE2000. f16 quantization is applied on every state update.", "",
"| Case | f32 (340 B) | f16 all (170 B) | f16 optics + f32 residual (176 B) | RGB roundtrip |",
"|---|---|---|---|---|"]
for case in ("reconstruction","mixture","white_tint","black_addition","four_colors","grouping_self_error","repeated_64","repeated_256","repeated_then_white","tiny_pickup_4096"):
    vals=[s["quality"][method][case] for method in ("f32","f16_all","f16_optics","rgb_roundtrip")]
    out.append("| "+case+" | "+" | ".join(f"{v['mean']:.5g} / {v['max']:.5g}" for v in vals)+" |")
out += ["", "Naive f16 is **rejected for iterative storage**. Ordinary mixtures look close,", 
"but a 0.0001 pickup fraction can disappear below its quantization step. Preserving", 
"the residual in f32 does not rescue the lost K/S updates. These unfavorable", 
"results are retained. No compressed state is enabled in the renderer.", "",
"## State access and memory", "",
"| Isolated operation | Median ns/state | Logical throughput GB/s |", "|---|---:|---:|"]
for op in ("mix_hot","decode_hot","rgb_roundtrip","read_sequential","read_scattered","update_sequential","update_scattered","copy_stream"):
    ns=median(kernel,"operation",op,"ns_per_op")
    count=next(int(x["logical_bytes_per_op"]) for x in kernel if x["operation"]==op)
    out.append(f"| {op} | {ns:.2f} | {count/ns:.2f}"+(" |" if count else " (not applicable) |"))
out += ["", "Sequential/scattered tests use 262,144 states (89.13 MB), fixed index patterns,", 
"seven repetitions after warmup. Read/write throughput counts logical bytes,", 
"not hardware-counter DRAM traffic; it must not be read as a bus measurement.", 
"Scatter is measurably more expensive. Cache brush and palette states, batch at", 
"stroke boundaries, and visit canvas rows coherently. Avoid an RGB-keyed cache", 
"for material history: equal RGB does not identify equal future mixtures.", "",
"| Canvas | Latent MB | Total resident canvas planes MB |", "|---|---:|---:|"]
for size,v in s["memory"]["canvases"].items(): out.append(f"| {size} | {v['latent_bytes']/1e6:.2f} | {v['canvas_bytes']/1e6:.2f} |")
out += ["", "The latent is verified at 340 bytes; the actual canvas is 373 bytes/pixel.", 
"These are decimal MB and exclude planner proxies, temporary lighting arrays,", 
"stroke buffers and snapshot compression. A 2400x3000 canvas alone costs 2.686 GB.",
"The original seven-float Mixbox renderer uses 57 bytes/pixel. The padded matched", 
"control intentionally does not represent Mixbox's minimum memory needs.", "",
"Fresh-process measurements at 600x690 (Windows working set, decimal MB):", "",
"| Method | Imported/encoded baseline | Peak painting | Peak painting + lighting |", "|---|---:|---:|---:|"]
for v in m.get("fresh_process_memory",[]):out.append(f"| {v['backend']} | {v['baseline_mb']:.1f} | {v['paint_peak_mb']:.1f} | {v['paint_light_peak_mb']:.1f} |")
out += ["", "## Validation and real scene", ""]
scene_comparison=R/"mixbox/scene/summary.json"
if scene_comparison.exists():
    v=json.loads(scene_comparison.read_text())
    out += [f"A second comparison replays the real scene's {v['strokes']:,} strokes at {v['width']} pixels "
            f"for {v['repeats']} repetitions. It decodes the authored source loads once to a shared RGB corpus, "
            "then re-encodes them for every method and regenerates authoring streaks. Geometry, seeds, brush settings "
            "and layer schedule are identical; planning is excluded.", "",
            "| Scene method | Paint seconds (median) | Lighting seconds (median) |", "|---|---:|---:|"]
    for name,r in v["backends"].items(): out.append(f"| {name} | {r['paint_seconds_median']:.3f} | {r['lighting_seconds_median']:.3f} |")
    out += ["", "![Same real scene strokes across mixers](../results/integration/mixbox/scene/scene-comparison.png)", ""]
vpath=R/"validation.json"
if vpath.exists():
    v=json.loads(vpath.read_text())
    out += [v["summary"], ""]
scene=R/"storm-run.json"
if scene.exists():
    v=json.loads(scene.read_text());t=v["timings"]
    out += [f"`storm_v3.py`: {v['strokes']:,} strokes, all 15 layers, 320-pixel planner and 600x750 output. "
            f"Total {t['total']:.2f} s; plan including snapshots {t['plan']:.2f} s; "
            f"snapshot writing {t.get('state_save',0):.2f} s; output replay {t['render']:.2f} s; final lighting {t['light']:.2f} s.",
            "The real-scene CLI timing is a single run and includes layer preparation in replay;", 
            "use the repeated brush measurements for timing comparisons. Full run metadata is retained.", "",
            "![Existing Storm Light scene rendered with Ochrell](../results/integration/storm-lit.png)", ""]
out += ["The earlier RGB-baseline smudge color gate and pre-fix Windows memory-probe", 
"failure are retained, not deleted. The Windows memory query was repaired; the", 
"RGB color gate is an existing baseline limitation, not an Ochrell regression.", "",
"## Next step and limits", "",
"The next highest-value step is **lossless storage and IO for large canvases**:",
"measure active tiles and preserve full f32 accumulators there, with independently", 
"verified lossless cold storage / snapshot streaming. Sparse allocation only saves", 
"memory when significant canvas regions remain untouched; a fully painted scene", 
"still needs a large material working set. Do not substitute naive f16.", "",
"After that, profile the complete raster path (including checked state import and", 
"coverage gamma conversion) before considering batched decoding or SIMD. Native", 
"Mixbox remains much cheaper, so a speed-parity claim would be unsupported.", "",
"This integration still uses a single exposed material, non-conserving pickup", 
"and heuristic depletion. Glaze is RGB compositing; height affects the renderer's", 
"surface, not Ochrell reflectance. No commercial paint calibration, physical", 
"glazing, production GPU implementation or measured browser performance is claimed.", "",
"See [integration/setup/reproduction](integration.md), [implementation plan](integration-plan.md),", 
"and `results/integration/mixbox/summary.json` for comparator scope and licensing.", ""]
(ROOT/"docs/integration-results.md").write_text("\n".join(out),encoding="utf-8")
print(ROOT/"docs/integration-results.md")
