"""v0.2 independent smooth reflectance reconstruction and optical prior.

Fits ONLY linear RGB cube anchors through our CIE integration matrix. No
Mixbox/Spectral.js data is read. Runtime requires no optimizer or LUT.
"""
import json, hashlib
import numpy as np
from scipy.optimize import lsq_linear, least_squares
from scipy.special import expit, logit
from model import ROOT, CFG, Model, prior, linear, srgb, gamut
TARGETS=np.array([[1,1,1],[0,1,1],[1,0,1],[1,1,0],[1,0,0],[0,1,0],[0,0,1],[0,0,0]])
O=CFG['optical']
def fit_basis():
 m=Model(O['reference_step_nm']);A=m.rgb.T;n=len(m.nm);D=np.diff(np.eye(n),axis=0)
 lo=O['reflectance_floor'];span=1-2*lo; fitted=[];records=[]
 for j in [4,5,6]:
  init=lsq_linear(np.vstack([A,O['initial_smoothing']*D]),np.r_[TARGETS[j],np.zeros(n-1)],bounds=(lo,1-lo),tol=1e-12,max_iter=500)
  z=logit(np.clip((init.x-lo)/span,.0001,.9999))
  def fun(z):return np.r_[A@(lo+span*expit(z))-TARGETS[j],O['logit_smoothing']*D@z]
  def jac(z):
   v=expit(z);return np.vstack([A*(span*v*(1-v))[None,:],O['logit_smoothing']*D])
  sol=least_squares(fun,z,jac=jac,max_nfev=2000,gtol=1e-12,ftol=1e-12,xtol=1e-12)
  if not sol.success:raise RuntimeError(sol.message)
  fitted.append(lo+span*expit(sol.x));records.append({'anchor':j,'evaluations':sol.nfev,'cost':sol.cost,'optimality':sol.optimality,'status':sol.message})
 r,g,b=fitted
 basis=np.array([np.full(n,1-lo),1-r,1-g,1-b,r,g,b,np.full(n,lo)])
 return basis,records
class OpticalModel:
 def __init__(self,basis,step=5,beta=None,white=None):
  self.m=Model(step);self.basis=np.array([np.interp(self.m.nm,Model(O['reference_step_nm']).nm,r) for r in basis])
  self.beta=O['beta'] if beta is None else beta;self.white=O['white_strength'] if white is None else white
 def encode(self,c):
  x=linear(c);r=np.array([prior(v)@self.basis for v in np.atleast_2d(x)]);e=np.atleast_2d(x)-r@self.m.rgb
  q=(1-r)**2/(2*r);y=r@self.m.xyz[:,1];sn=2*y/(1+y*y)
  s=(1+q)**(-self.beta)*sn[:,None]**(1-self.beta)*(1+(self.white-1)*np.min(np.atleast_2d(x),axis=1))[:,None]
  return q*s,s,e
 def decode(self,z,raw=False,residual=True):
  k,s,e=z;q=k/s;r=1/(1+q+np.sqrt(q*(q+2)));x=r@self.m.rgb+(e if residual else 0)
  return x if raw else gamut(x)
 def mix(self,a,b,t,raw=False,residual=True):
  a=self.encode(a);b=self.encode(b);t=np.asarray(t)
  if t.ndim:t=t[:,None]
  return self.decode(tuple((1-t)*x+t*y for x,y in zip(a,b)),raw,residual)
def rust_array(x):
 x=np.asarray(x)
 if x.ndim==0:return format(float(x),'.17e')
 return '['+','.join(rust_array(v) for v in x)+']'
def generate():
 if O['beta']!=.5:raise ValueError('Rust optimized kernel currently requires optical.beta=0.5')
 if O['reference_step_nm']!=5 or O['fast_step_nm'] not in [5,10,20]:raise ValueError('reference step must be 5; fast step 5, 10 or 20')
 if not 0<O['reflectance_floor']<.1 or O['white_strength']<1:raise ValueError('Invalid optical bounds')
 b,records=fit_basis();out=ROOT/'results/revision';out.mkdir(parents=True,exist_ok=True)
 np.savetxt(ROOT/'data/optical_basis.csv',np.c_[Model(5).nm,b.T],delimiter=',',header='nm,W,C,M,Y,R,G,B,K',comments='',fmt='%.17g')
 lines=['// Generated by tools/optical_model.py from CIE colorimetry; see docs/coefficients.md.',f'pub const WHITE_STRENGTH: f64 = {O["white_strength"]:.17e};']
 for label,step,ty in [('REF',5,'f64'),('FAST',O['fast_step_nm'],'f32')]:
  m=OpticalModel(b,step);n=len(m.m.nm)
  lines.extend([f'pub const {label}_N: usize = {n};',f'pub const {label}_BASIS: [[{ty}; {n}]; 8] = {rust_array(m.basis)};',f'pub const {label}_RGB: [[{ty}; 3]; {n}] = {rust_array(m.m.rgb)};',f'pub const {label}_Y: [{ty}; {n}] = {rust_array(m.m.xyz[:,1])};'])
 (ROOT/'src/optical_generated.rs').write_text('\n'.join(lines)+'\n')
 report={'optimization':records,'config':O,'anchor_linear_errors':(b@Model(5).rgb-TARGETS).tolist(),'basis_sha256':hashlib.sha256((ROOT/'data/optical_basis.csv').read_bytes()).hexdigest()}
 (out/'generation.json').write_text(json.dumps(report,indent=2)+'\n')
 return b
if __name__=='__main__':generate()
